name       : perl-template
version    : 2.29
release    : 3
source     :
    - https://github.com/abw/Template2/archive/v2.29.tar.gz : d1627c8002a490afb9b902ac313061000f6ea98889f4dd018eef47f93c114a2e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Fast, flexible, powerful and extensible template processing system
description: |
    The Template Toolkit is a collection of modules which implement a fast, flexible, powerful and extensible template processing system.
    It was originally designed and remains primarily useful for generating dynamic web content, but it can be used equally well for processing any other kind of text based documents: HTML, XML, POD, PostScript, LaTeX, and so on.
builddeps  :
    - perl
rundeps    :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
